# ===========================================
# ToastedAD Configuration
# ===========================================

# Thank you for using ToastedAD!
# For support join our discord server and create a ticket
# ➥ discord.gg/dn8YE2Ctbv

# Permissions Configuration
# -------------------------
Permissions:
  coral:  # Permission node will be: toastedad.perms.coral
    cooldown: 60  # Cooldown time in seconds
    format: false  # Whether the player can use formatting codes (&l, &m, etc.)
    color: true   # Whether the player can use color codes (&7, &6, etc.)
    
    # Sound Settings
    # For a list of available sounds, refer to:
    # 1.8.8+: https://helpch.at/docs/1.8.8/org/bukkit/Sound.html
    # 1.17.1+: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
    sound:
      value: ENTITY_BAT_DEATH  # The sound to play
      pitch: 1.0F  # Pitch of the sound (0.5 to 2.0)
      volume: 1.0F  # Volume of the sound (0.0 to 1.0)

# Message Configuration
# ---------------------
Messages:
  no_perms: "&cYou don't have permission to use this command!"
  advertise_message:
    - " "
    - "[AD] {player} {message}"  # {player} and {message} will be replaced
    - " "
  usage: "Usage: /ad {message}"
  check_cooldown: "You must wait {cooldown} seconds before you can advertise again"
  cooldown: "You must wait {cooldown} seconds before you can advertise again"
  
  # List of worlds where advertising is allowed
  worlds_allowed:
    - "world"
    - "nether"
    - "end"
    # Add more worlds as needed