Permissions:
  coral: # the perms will be toastedad.{something}
    cooldown: 60
    format: false # if the player can use &l &m
    color: true # if the player can use &7 &6 etc.

    # 1.8.8+ Sounds -> https://helpch.at/docs/1.8.8/org/bukkit/Sound.html
    # 1.17.1+ Sounds -> https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
    sound:
      value: ENTITY_BAT_DEATH
      pitch: 1.0F
      volume: 1.0F

Messages:
  no_perms: "&cYou don't have permission to use this command!"
  advertise_message:
    - " "
    - "[AD] {player} {message}"
    - " "
  usage: "Usage: /ad {message}"
  check_cooldown: "You must wait {cooldown} seconds before you can advertise again"
  cooldown: "You must wait {cooldown} seconds before you can advertise again"

